Спринт № 10
steelzhi/java-filmorate pull request #2
Opened 2023-03-18 11:59 UTC by steelzhi

2023-03-19 08:36 UTC, mikita95 requested changes
В целом, все верно :) Нужно лишь исправить небольшое косметические моменты.

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService;
Лучше все же в контроллере оставить только сервис, так получается, что логику размазана по двум классам. Да, придется добавить методы создания и получения сущностей в сервис - но это тоже по сути, часть бизнес-логики. В будущем, например, эти методы могут кешироваться или обрасти дополнительной логикой. Так сервис является "фасадом" между слоем контроллера и хранения данных.

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Аналогичное замечание, как и в FilmController - лучше оставить здесь только сервис

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserStorage getUserStorage() {
Этого метода быть не должно. Так как вы используете спринг и по-умолчанию все компоненты создаются как "синглетон", то есть существует только один экземпляр на весь контекст спринга.
Тогда где нужно, можно просто заинжектить UserStorage

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Long friendId : friendsIds) {
Этот кусочек можно было бы переписать в функциональном стиле - было бы чуть короче, но и так хорошо)

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private Map<Long, User> users;
У вас есть класс-хранилище - нужно хранить пользователей только там :)

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmStorage getFilmStorage() {
Этого метода быть не должно. Так как вы используете спринг и по-умолчанию все компоненты создаются как "синглетон", то есть существует только один экземпляр на весь контекст спринга.
Тогда где нужно, можно просто заинжектить FilmStorage

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            System.out.println(selectedFilms);
Лучше не оставлять в готовом решении прямого вывода в консоль, лучше просто писать в лог - так можно перенаправить поток лога куда угодна, и вывод структурированнее

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Collections.sort(sortedListByLikesCount, (o1, o2) -> {
Компаратор можно вынести в константы класса и не создавать каждый раз

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Long> userLikes = new ArrayList<>();
Можно пометить это поле как `@JsonIgnore` из `com.fasterxml.jackson.annotation.JsonIgnore` - это поле не нужно на клиентской стороне и его не нужно передавать или получать

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Long> userLikes = new ArrayList<>();
Можно пометить это поле как `@JsonIgnore` из `com.fasterxml.jackson.annotation.JsonIgnore` - это поле не нужно на клиентской стороне и его не нужно передавать или получать

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> friendsIds = new HashSet<>();
Можно пометить это поле как `@JsonIgnore` из `com.fasterxml.jackson.annotation.JsonIgnore` - это поле не нужно на клиентской стороне и его не нужно передавать или получать

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Autowired
Здесь можно не писать @Autowired в данном случае, так как поля помечены final, есть только один конструктор и у спринга нет другого варианта как создать экземпляр класса.

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private void checkFilmParams(Film film) {
В данном случае, это часть бизнес логики, и вся валидации проводится там, лучше перенести валидацию в сервис. А здесь в хранилище оставить только логику хранения данных

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return films;
Лучше выдавать копию данных или список, иначе это небольшое нарушение инкапсуляции и можно поменять состояние хранилища не через методы интерфейса

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    @PutMapping("/users")
Это не контроллер и здесь не должно быть такого маппинга :)

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    private void checkUserParams(User user) {
В данном случае, это часть бизнес логики, и вся валидации проводится там, лучше перенести валидацию в сервис. А здесь в хранилище оставить только логику хранения данных

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return users;
Лучше выдавать копию данных или список, иначе это небольшое нарушение инкапсуляции и можно поменять состояние хранилища не через методы интерфейса

2023-03-19 08:36 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public Long getId() {
Не уверен, что этот метод нужен :) Но, в целом, ничего плохого в нем нет, но лучше возвращать примитивный тип long - так надежнее

2023-03-20 05:52 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService;
> В целом, все верно :) Нужно лишь исправить небольшое косметические моменты.

Никита, здравствуйте!
Спасибо за ревью:) Все поправил, проверьте, пожалуйста.

2023-03-20 05:53 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService;
> Лучше все же в контроллере оставить только сервис, так получается, что логику размазана по двум классам. Да, придется добавить методы создания и получения сущностей в сервис - но это тоже по сути, часть бизнес-логики. В будущем, например, эти методы могут кешироваться или обрасти дополнительной логикой. Так сервис является "фасадом" между слоем контроллера и хранения данных.

Исправил.

2023-03-20 05:54 UTC, steelzhi commented
Никита, здравствуйте!
Спасибо за ревью:) Все поправил, проверьте, пожалуйста.

2023-03-20 05:54 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService;
Исправил.

2023-03-20 05:54 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Исправил.

2023-03-20 05:54 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserStorage getUserStorage() {
Исправил.

2023-03-20 05:54 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Long friendId : friendsIds) {
Да, не увидел) Переделал.

2023-03-20 05:55 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private Map<Long, User> users;
Исправил.

2023-03-20 05:55 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return films;
Интересно, не думал об этом) Исправил.

2023-03-20 05:55 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    @PutMapping("/users")
Остался от копирования сигнатур методов) Исправил.

2023-03-20 05:56 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    private void checkUserParams(User user) {
Исправил.

2023-03-20 05:56 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return users;
Исправил.

2023-03-20 05:56 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public Long getId() {
Да, действительно не нужен) Убрал его.

2023-03-20 05:56 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmStorage getFilmStorage() {
Исправил.

2023-03-20 05:57 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            System.out.println(selectedFilms);
Это у меня был "костыль" для поиска одной ошибки - забыл его удалить) Исправил.

2023-03-20 05:57 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Collections.sort(sortedListByLikesCount, (o1, o2) -> {
Исправил.

2023-03-20 06:01 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Long> userLikes = new ArrayList<>();
Исправил.

2023-03-20 06:02 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Long> userLikes = new ArrayList<>();
Исправил.

2023-03-20 06:02 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> friendsIds = new HashSet<>();
Исправил.

2023-03-20 06:02 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Autowired
Понятно. Исправил.

2023-03-20 06:02 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private void checkFilmParams(Film film) {
Исправил.

2023-03-20 19:35 UTC, mikita95 approved these changes
Все верно :) Можно мержить пул-реквест.

2023-03-21 12:25 UTC, merged