Добавление БД к приложению
steelzhi/java-filmorate pull request #4
Opened 2023-04-16 14:00 UTC by steelzhi

Добавления БД для возможности постоянного хранения информации из приложения.

2023-04-16 22:22 UTC, mikita95 requested changes
Все сделано хорошо. Нужно лишь поправить несколько моментов небольших

2023-04-16 22:22 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    public List get() {
Не хватает типа элtментов списка :) Также стоит отметить метод аннотацией `@Override`

2023-04-16 22:22 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        return mpaStorage.create(mpa);
Кажется, здесь должен быть update :)

2023-04-16 22:22 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +            if (mpa.getId() == mpaId) {
Можно лучше: сейчас во всех местах существование проверяется получением всего списка данных. Это не очень эффективно, если данных много, то будет работать медленно и затратно по памяти. Можно сделать в хранилищах методы для проверки существования и проверять в базе с помощью операции exists

2023-04-16 22:22 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            for (Genres genres : film.getGenres()) {
Кажется, что эти два цикла можно заменить на ` List<Genres> genres = new ArrayList<>(film.getGenres());`

2023-04-16 22:22 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public Set<Long> addFriend(Long id, Long friendId) {
Стоит пометить метод как `@Override`

2023-04-16 22:22 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public Set<Long> deleteFriend(Long id, Long friendId) {
Стоит пометить метод как `@Override`

2023-04-17 13:04 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            for (Genres genres : film.getGenres()) {
Эти циклы нужны, чтобы при помощи промежуточного HashSet оставить только неповторяющиеся id жанров (на входе у нас может быть ArrayList с повторяющимися id жанров, а на выходе уже будет с неповторяющимися).

2023-04-17 13:45 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    public List get() {
Исправил.

2023-04-17 13:45 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        return mpaStorage.create(mpa);
Забыл поправить при копировании) Исправил.

2023-04-17 13:52 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +            if (mpa.getId() == mpaId) {
Перенес проверки в хранилища, убрал загрузку всех списков данных.

2023-04-17 13:53 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public Set<Long> addFriend(Long id, Long friendId) {
Исправил.

2023-04-17 13:53 UTC, steelzhi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public Set<Long> deleteFriend(Long id, Long friendId) {
Исправил.

2023-04-17 14:28 UTC, steelzhi commented
Никита, спасибо за ревью. Исправления внес, проверьте, пожалуйста.
P.S. В классе FilmDbStorage в методе mapRowToFilm мне пришлось заполнить блоки catch (хотя для работы моей программы это не требуется) - иначе при проверке на github код не мог пройти раздел "Checkstyle" (в котором запрограммировано, что блоки catch не должны быть пустыми).

2023-04-17 15:34 UTC, mikita95 approved these changes
Все работает верно. Можно мержить пул-реквест.

2023-04-18 12:43 UTC, merged